sudo: false
language: php
os:
  - linux
php:
  - 7.3
before_script:
  - make setup
  - composer self-update
  - composer install --prefer-dist
script: vendor/bin/phpunit
notifications:
  email: false
